version: "2"
services:
  notebooks:
    build: .
    volumes:
      - notebooks:/home/jovyan/notebooks
      - ${SRCDIR}:/home/jovyan/plotly-adjunct
    ports:
      - "8870:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    #entrypoint: ["jupyter", "notebook"]
    command: bash -c "pip install -e ./plotly-adjunct && jupyter notebook"
  lab:
    build: .
    volumes:
      - notebooks:/home/jovyan/notebooks
      - ${SRCDIR}:/home/jovyan/plotly-adjunct
    ports:
      - "8872:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    #entrypoint: ["jupyter", "lab"]
    command: bash -c "pip install -e ./plotly-adjunct && jupyter lab"

volumes:
  notebooks:
